version: '3'
services:

  postgres:
    container_name: my-db
    environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
    image: postgres:13.1-alpine
    restart: unless-stopped
    ports:
        - ${POSTGRES_PORT}:${POSTGRES_PORT}/tcp
    volumes:
        - ${PWD}/solita-db:/var/lib/postgresql/data 

  flyway:
    container_name: my-flyway
    environment:
        - FLYWAY_USER=${POSTGRES_USER}
        - FLYWAY_PASSWORD=${POSTGRES_PASSWORD}
        - FLYWAY_URL=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_DB}
        - FLYWAY_SCHEMAS=flyway,${POSTGRES_SCHEMA}
        - FLYWAY_GROUP=true
    image: flyway/flyway:latest
    command: -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    volumes:
        - $PWD/sql_versions:/flyway/sql
    depends_on:
        - postgres

  solita-backend:
    build:
      context: ./solitaExpress
    restart: unless-stopped
    environment:
      - DB_SCHEMA=flyway
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=postgres
    depends_on:
      - postgres
    ports:
      - '3001:3000'

  solita-frontend:
    build:
      context: ./solitaFrontend
    restart: unless-stopped
    depends_on:
      - solita-backend
      - postgres
    ports:
      - '19000:19000'
      - '19001:19001'
      - '19002:19002'
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0

volumes:
  solita-db:
