version: '3'
services:

  postgres:
    container_name: my-db
    environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
    image: postgres:13.1-alpine
    restart: unless-stopped
    ports:
        - ${POSTGRES_PORT}:${POSTGRES_PORT}/tcp
    volumes:
        - ${PWD}/solita-db:/var/lib/postgresql/data 

  flyway:
    container_name: my-flyway
    environment:
        - FLYWAY_USER=${POSTGRES_USER}
        - FLYWAY_PASSWORD=${POSTGRES_PASSWORD}
        - FLYWAY_URL=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_DB}
        - FLYWAY_SCHEMAS=flyway,${POSTGRES_SCHEMA}
        - FLYWAY_GROUP=true
    image: flyway/flyway:latest
    command: -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    volumes:
        - $PWD/sql_versions:/flyway/sql
    depends_on:
        - postgres

volumes:
  solita-db:
