version: '3.7'
services:
    postgres:
      image: postgres
      restart: unless-stopped
      ports:
        - 5432:5432
      environment:
        POSTGRES_USER: solita
        POSTGRES_PASSWORD: solita
      volumes:
          - solita-db:/var/lib/postgresql/data

    solita:
      build:
        context: .
      environment:
        DB_SCHEMA: solita
        DB_USER: solita
        DB_PASSWORD: solita
        DB_HOST: postgres
      depends_on:
        - postgres
      ports:
        - '3000:3000'


volumes:
  solita-db: